spring:
  profiles:
    active: dev

---

spring:
  profiles: prod
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.101:3306/lexicon
    username: lexicon
    password: lexicon1

---

spring:
  profiles: dev
  #datasource:
    #driverClassName: org.h2.Driver
    #url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;Mode=MySQL5Dialect;DATABASE_TO_UPPER=false;
    #username: sa
    #schema: classpath:/schema.sql
  jpa:
      #database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
      generate-ddl: true
    properties:
      hibernate.jdbc.use_get_generated_keys: true
      javax.persistence.validation.mode: none
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
#  datasource:
#    data: classpath:/init.sql

  ###
  #   H2 Settings
  ###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
#spring:
#  hibernate:
#    dialect: org.hibernate.dialect.MySQL5Dialect
#    show_sql: true
#    format_sql: true
#  logging:
#    level:
#      org:
#        hibernate:
#          SQL: DEBUG
#          type:
#            descriptor:
#              sql:
#                BasicBinder: TRACE
