server:
  port: 8080

spring:
  profiles:
    active: h2, db_log
  application:
    name: LexiconService
  h2:
    console:
      enabled: true


#---
#
#spring:
#  profiles: prod
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.56.101:3306/lexicon
#    username: lexicon
#    password: lexicon1

---

spring:
  profiles: mysql
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.101:3306/lexicon
    username: lexicon
    password: lexicon1

---

spring:
  profiles: dev
  #datasource:
    #driverClassName: org.h2.Driver
    #url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;Mode=MySQL5Dialect;DATABASE_TO_UPPER=false;
    #username: sa
    #schema: classpath:/schema.sql
    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;Mode=Oracle;DATABASE_TO_UPPER=false;
#    username: sa
#    password:
#    schema: schema.sql
  jpa:
      #database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
      generate-ddl: true
    properties:
      hibernate.jdbc.use_get_generated_keys: true
      javax.persistence.validation.mode: none
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
#  datasource:
#    data: classpath:/init.sql

  ###
  #   H2 Settings
  ###
---
spring:
  profiles: h2

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          use_get_generated_keys: true
        javax:
          persistence:
            validation:
              mode: none
  datasource:
    data: classpath:/init.sql

---
spring:
  profiles: db_log

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        type: trace
  logging:
    level:
      org:
        hibernate:
          type: trace